name: Deploy to Personal Repository

on:
  push:
    branches: ['main']

jobs:
  deploy-to-personal-repo:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Copy Files to Personal Repository
        uses: actions/checkout@v4
        with:
          repository: 1eeyerin/BloodFolio
          token: ${{ secrets.PERSONAL_REPO }}
          path: 'tmp_repo'

      - name: Copy Files to Personal Repository
        run: rsync -av --exclude=".git" --exclude=".github" --exclude="dist" --exclude="node_modules" ./ tmp_repo/

      - name: Push to Personal Repository
        run: |
          cd tmp_repo
          git config --local user.email ${{ secrets.OFFICIAL_EMAIL }}
          git config --local user.name 'GitHub Actions'
          git add .
          git commit -m 'Deploy Build Output to Personal Repository'
          git push origin main
